### PR TITLE
allow and build with Rails 7.1

### PR DESCRIPTION
**Pull request by jrochkind**

### CODE REVIEW

**Comment by jrochkind** [comment]
OK, locally this is failing the _same_ 5 tests for both Rails 7.0 and 7.1. 

So whatever the failure is in those versions is not new to Rails 7.0 and 7.1. I will see what I can do first in other PR.

**Comment by jrochkind** [comment]
Fixed at least one pre-existing problem at #385  , rebasing

**Comment by jrochkind** [comment]
OK, this is a weird failure. 

```
 #  from /home/circleci/project/.internal_test_app/Gemfile:39
 #  -------------------------------------------
 #  # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
 >  gem "tzinfo-data", platforms: %i[ windows jruby ]
 #  
 #  -------------------------------------------

[!] There was an error parsing `Gemfile`: `windows` is not a valid platform. The available options are: [:ruby, :ruby_18, :ruby_19, :ruby_20, :ruby_21, :ruby_22, :ruby_23, :ruby_24, :ruby_25, :ruby_26, :mri, :mri_18, :mri_19, :mri_20, :mri_21, :mri_22, :mri_23, :mri_24, :mri_25, :mri_26, :rbx, :truffleruby, :jruby, :jruby_18, :jruby_19, :mswin, :mswin_18, :mswin_19, :mswin_20, :mswin_21, :mswin_22, :mswin_23, :mswin_24, :mswin_25, :mswin_26, :mswin64, :mswin64_19, :mswin64_20, :mswin64_21, :mswin64_22, :mswin64_23, :mswin64_24, :mswin64_25, :mswin64_26, :mingw, :mingw_18, :mingw_19, :mingw_20, :mingw_21, :mingw_22, :mingw_23, :mingw_24, :mingw_25, :mingw_26, :x64_mingw, :x64_mingw_20, :x64_mingw_21, :x64_mingw_22, :x64_mingw_23, :x64_mingw_24, :x64_mingw_25, :x64_mingw_26]. Bundler cannot continue.
```

The engine-cart generated gem has "windows" as a platform... I think that actually just comes from `rails new` doesn't it? And then this version of bundler does not like it?

I think we have too old a version of bundler running in circleci for Rails 7.1-generated app... I have no idea how to update it.

**Comment by jrochkind** [comment]
Ah, wait, it’s maybe that we are using [DEPRECATED] samvera/bundle_for_gem in the circleci setup. So maybe I just need to figure out how to switch that….

**Comment by jrochkind** [comment]
OK, for platform windows we need at least bundler 2.3.22 https://github.com/rubygems/rubygems/blob/3.4/bundler/CHANGELOG.md#2322-september-7-2022

We currently have 2.3.10. This is fixable!

**Comment by jrochkind** [comment]
Including workaround for https://github.com/cbeer/engine_cart/issues/117

**Review by dlpierce — APPROVED** [review]

**Comment by jrochkind** [comment]
Thank you @dlpierce !

**Pull request merged**
