### PR TITLE
Fix deprecation

### PR DESCRIPTION
**Pull request by bbarberBPL**
I'm currently refactoring one of our gems and qa v2.2. However when running the tests I kept getting 

```/home/bbarber/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/qa-3.0.0/lib/qa/authorities/loc/generic_authority.rb:27:in `build_query_u
rl': warning: URI.escape is obsolete
/home/bbarber/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/qa-3.0.0/lib/qa/authorities/loc/generic_authority.rb:28:in `build_query_url'
: warning: URI.escape is obsolete
/home/bbarber/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/qa-3.0.0/lib/qa/authorities/loc/generic_authority.rb:27:in `build_query_url'
: warning: URI.escape is obsolete
/home/bbarber/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/qa-3.0.0/lib/qa/authorities/loc/generic_authority.rb:28:in `build_query_url'
: warning: URI.escape is obsolete```

I bumped the version up in my `gemspec` to the latest release and found i was getting the same warnings in my tests 

Doing further research online I found on the ruby docs [here](https://ruby-doc.org/stdlib-2.4.0/libdoc/uri/rdoc/URI/Escape.html)  That as of 2.4.0 this method has been deprecated and is now obsolete. Since I am running on 2.4.5 I first was able to make a monkey patch in the gem. But my colleague advised me to inform the Samvera community about this. I also removed a duplicate declaration of `simplecov` that was listed in both the `gemspec` and the `Gemfile`

I was able to set up engine cart and run the specs and all of them passed.  I created a method in the web_service_base module that will maintain backwards compatibility for earlier ruby versions but for anyone using 2.4.0 and above it will use `CGI.escape` instead of `URI.escape`.

### CODE REVIEW

**Comment by elrayle** [comment]
@bbarberBPL Thanks for submitting this.  I am in the process of working on a major refactor for QA which will likely delay the release of this.  How critical is it for you to get this in place?  Can it wait a while for the full refactor to be completed?

**Comment by bbarberBPL** [comment]
@elrayle  Yeah that's no problem for us I can use the monkey patch I have in place for the gem thats dependent on this for now.

**Comment by elrayle** [comment]
I spoke with several folks in Slack.  There was general agreement that `ERB::Util.url_encode` produces the same behavior as the deprecated `URL::escape`.  For that reason, the deprecation will be resolved using ERB as the replacement.  There are a number of places beyond the one addressed in this PR.

**Comment by elrayle** [comment]
Interestingly, the URI.escape method itself has this recommendation...

> "This method is obsolete and should not be used. Instead, use CGI.escape, URI.encode_www_form or URI.encode_www_form_component depending on your specific use case."

**Comment by elrayle** [comment]
More info...

```
>> require 'addressable/uri'
=> false
>> Addressable::URI.escape 'http://google.com/foo?bar=at#anchor&title=My Blog & Your Blog'
=> "http://google.com/foo?bar=at#anchor&title=My%20Blog%20&%20Your%20Blog"
>>
>> URI.escape 'http://google.com/foo?bar=at#anchor&title=My Blog & Your Blog'
=> "http://google.com/foo?bar=at%23anchor&title=My%20Blog%20&%20Your%20Blog"
>>
>> CGI.escape 'http://google.com/foo?bar=at#anchor&title=My Blog & Your Blog'
=> "http%3A%2F%2Fgoogle.com%2Ffoo%3Fbar%3Dat%23anchor%26title%3DMy+Blog+%26+Your+Blog"
>>
>> ERB::Util.url_encode 'http://google.com/foo?bar=at#anchor&title=My Blog & Your Blog'
=> "http%3A%2F%2Fgoogle.com%2Ffoo%3Fbar%3Dat%23anchor%26title%3DMy%20Blog%20%26%20Your%20Blog"
```

From this, if you want to encode a URL to be passed to CURL as the URL, use Addressable.  If you want to encode a URL to pass as a parameter to another URL, then use either CGI or ERB.

**Comment by elrayle** [comment]
This was addressed by PR #210.

**Pull request closed without merging**
