### PR TITLE
Replace URI.unescape with CGI.unescape

### PR DESCRIPTION
**Pull request by eddierubeiz**
(issue description by jrochkind)

`URI.unescape` does not exist anymore in ruby 3.1, after having been long-deprecated.  

There are a variety of other ways in stdlib to do some kind of html-related `unescape`, but none have the exact same semantics. 

It is hard to know which we want -- when we don't understand why this `unescape` is here in the first place. Why would an in-memory `id` in the `LinkedData::FindTerm` authority be in an escaped form, and need unescaping before doing... other things that honestly we're not sure what they're doing, which doesn't make it easier to know what form of escaping, if any, is necessary here. 

All tests pass without any unescaping, there are no tests that require escaping, so that doesn't answer the question of why escaping is being done here, and what form it should be in. 

My inclination is to think that the escaping was unnecessary or even a bug (or a workaround to a bug somewhere else?), and should simply be removed. 

If that causes a problem for someone in a real-world use-case, that use case might help us understand why escaping was there in the first place, and the best way to fix it.  But without a report of such a case... remove the `unescape` call for ruby 3.1 compatibility?

### CODE REVIEW

**Comment by jrochkind** [comment]
@eddierubeiz Can you also actually edit the COMMIT MESSAGE the commit where you remove URI.unescape, to explain the motivation/justificaition for removing it, at just a short summary or something? Something more than a commit message saying "remove URI.unescape". 

i want to leave something better in the commit message for someone who comes later and is like "Why did they remove this??" -- having been in that position in the past. 

You can use git rebase to rewrite commit messages I think.

**Comment by jrochkind** [comment]
Thanks @dlpierce , good find!

I wish I understood what that comment meant, but I don't!  

Do you have any advice for what should be done here with `URI.unescape` no longer being available in the stdlib?  

> '%20' is changed to ' ', and '%2E' is changed to '.', etc.

We could write a routine that did those specifically... or do we need a routine that does any/all percent-encoding? Or what? 

We can just replace with some alternate stdlib method like`CGI.unescape`, but that one for instance won't actually properly unescape `%20` so that one isn't it... 

Any advice for us would be most welcome @dlpierce

**Comment by eddierubeiz** [comment]
I replaced `URI.unescape` with `CGI.unescape`. I'll see if I can add a test for `find_term_spec.rb` to shore all of this up a bit.

**Comment by eddierubeiz** [comment]
I'm hoping the docs at https://github.com/samvera/questioning_authority/wiki/Using-the-Linked-Data-module-to-access-authorities provide with enough info to be able to figure out a decent use case that can be used in a test. I'm going to tinker with this for a bit.

**Comment by eddierubeiz** [comment]
I'm going to recommend we replace the three instances of `URI.unescape` with `CGI.unescape` unless anyone else has strong feelings about it.

I've spent some time configuring and using this code, and I do understand how it works somewhat better now (at least in the LOC case).  I do concur that it's quite possible the first `unescape` is in fact not needed and could be replaced by a `dup`. But I don't feel comfortable doing it without spending more time tinkering with the code -- and I'm unfortunately running out of time :) .

Re: `CGI.unescape` versus some other (non-obsolete) escaping recipe: based on a quick survey of the form of RDF predicates at LOC and OCLC,  mapping a `+` in the `id` property with a space in this class is unlikely to prevent any matches from occurring. Again it's tough to say for sure without a more robust set of tests for this class -- and, in turn, I really can't write those tests without a better understanding of real-world use-cases.

**Review by dlpierce — APPROVED** [review]

**Pull request merged**
