### PR TITLE
allow rails 6.2

### LINKED ISSUE #330: support Rails 6.1?
Hi, the qa gemspec says `'rails', '>=5.0', "< 6.1"`

Rails 6.1.0 final is out, December 9, 2020. 

There aren't very many backwards incompat changes in Rails 6.1, it's possible qa works fine with it, and just requires a gemspec change and new release?

I can try doing a PR that does nothing but a gemspec chagne to see if it passes?

### PR DESCRIPTION
**Pull request by jrochkind**
This PR does nothing except change the gemspec to allow Rails 6.1. Curious if CI will pass like this?

I am unable to run tests locally per #331, so this is a way to see if CI will run tests for me to see what happens, sorry. 

Closes #330

### CODE REVIEW

**Comment by jrochkind** [comment]
Ah, circleci would have to be changed to actually run tests under rails 6.1 too. 

I am not too familiar with circle-ci, but i'll see if I can figure it out.

**Comment by jrochkind** [comment]
Rails 6.1 build seems to fail with:

```
Don't know how to build task 'webpacker:install' (See the list of available tasks with `rails --tasks`)
```

I'm not sure what's going on there, why webpacker:install wouldn't be available if it was really a rails 6.1 app (or even a rails 6.0 app) that engine cart was creating... so maybe it's not somehow?  This is beyond the quick fix I was hoping for, so I guess it's demonstrated it needs more than just a gemspec change to work with rails 6.1. 

I am also not sure how to control what jobs show up as "required" in github list above; some do some don't, the new 6.1 one does not.

**Comment by jrochkind** [comment]
in my own app, if I fork qa to allow rails 6.1, and upgrade to rails 6.1.... my own apps tests pass, and it's functionality supported by qa works fine. I think it's possible this is just a test setup issue, and qa actually works fine with rails 6.1.

**Comment by jrochkind** [comment]
Huh wait a seccond, rails 6-1 test is showing up green in github here. 

And weird, when I click on it... it looks like it was passing in circleci?? Not sure why I swear I saw it failing before!

So... maybe qa passes tests fine on railas 6.1 and just needs a merge and release?

**Review by elrayle — APPROVED** [review]
Looks good.

**Comment by jrochkind** [comment]
Thank you! And for quick release, that's so helpful, I appreciate it! 

Corrected title of this PR, it allows rails 6.1, not 6.2.

**Pull request merged**
