### PR TITLE
Updates the CircleCI configuration to test against Ruby releases 2.6.3, 2.5.5, and 2.4.6

### LINKED ISSUE #242: Test against Ruby releases 2.6.3, 2.5.5, and 2.4.6
Derived from samvera/maintenance#17

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Resolves #242

### CODE REVIEW

**Comment by randalldfloyd** [comment]
@jrgriffiniii I usually help keep PR's moving through for QA but I don't know what to make of the current status on checks.

**Comment by jrgriffiniii** [comment]
I'm sorry for that, I'll investigate this and see about restarting the build.

**Comment by randalldfloyd** [comment]
Thanks!  I was going to try to kick it to wake it up but it looks like I don't have ability to do that in Circle.  Not sure if I should or not, plus I didn't know if it was just an anomaly or you were still playing with configuration.

**Comment by jrgriffiniii** [comment]
The branch settings still expecting reports from CircleCI Jobs which ran against Rails 5.0.x releases (which this PR removes), along with some other deprecated CircleCI Jobs.  I still need to see about why Coveralls is not reporting for this.

**Comment by jrgriffiniii** [comment]
Coveralls is now reporting for this PR.

**Pull request merged**
